@startuml

package "OperacoesUsuario" {
  [CadastroView]
  [LoginView]
  [DashboardAlunoView]
  [DashboardProfessorView]
  [DashboardEmpresaView]
  [AuthController]
  [UsuarioController]
  [AlunoController]
  [AlunoService]
  [AlunoRepository]
  [ProfessorController]
  [ProfessorService]
  [ProfessorRepository]
  [EmpresaController]
  [EmpresaService]
  [EmpresaRepository]
  [Usuario]
  [Aluno]
  [Professor]
  [Empresa]
  [Instituicao]
}

package "OperacoesFinanceiras" {
  [ExtratoView]
  [TrocaMoedaView]
  [VantagemController]
  [VantagemService]
  [VantagemRepository]
  [TransacaoController]
  [TransacaoService]
  [TransacaoRepository]
  [Vantagem]
  [Transacao]
  [Cupom]
}

' View -> Controller
[LoginView] ..> [AuthController]
[DashboardAlunoView] ..> [AlunoController]
[DashboardProfessorView] ..> [ProfessorController]
[DashboardEmpresaView] ..> [EmpresaController]
[ExtratoView] ..> [TransacaoController]
[TrocaMoedaView] ..> [VantagemController]
[CadastroView] ..> [UsuarioController]

' Controller -> Service
[AuthController] ..> [Usuario]
[UsuarioController] ..> [Usuario]
[AlunoController] ..> [AlunoService]
[ProfessorController] ..> [ProfessorService]
[EmpresaController] ..> [EmpresaService]
[VantagemController] ..> [VantagemService]
[TransacaoController] ..> [TransacaoService]

' Service -> Repository
[AlunoService] ..> [AlunoRepository]
[ProfessorService] ..> [ProfessorRepository]
[EmpresaService] ..> [EmpresaRepository]
[VantagemService] ..> [VantagemRepository]
[TransacaoService] ..> [TransacaoRepository]

' Repository -> Model
[AlunoRepository] ..> [Aluno]
[AlunoRepository] ..> [Instituicao]
[AlunoRepository] ..> [Cupom]
[ProfessorRepository] ..> [Professor]
[ProfessorRepository] ..> [Transacao]
[EmpresaRepository] ..> [Empresa]
[EmpresaRepository] ..> [Vantagem]
[VantagemRepository] ..> [Vantagem]
[TransacaoRepository] ..> [Transacao]
[TransacaoRepository] ..> [Usuario]

' Herança
[Usuario] <|-- [Aluno]
[Usuario] <|-- [Professor]
[Usuario] <|-- [Empresa]

@enduml
