@startuml
skinparam componentStyle rectangle

package "View" {
  [LoginPage]
  [DashboardAluno]
  [DashboardProfessor]
  [DashboardEmpresa]
  [ExtratoView]
  [TrocaMoedaView]
  [CadastroAlunoView]
}

package "Controller" {
  [AuthController]
  [AlunoController]
  [ProfessorController]
  [EmpresaController]
  [VantagemController]
  [TransacaoController]
}

package "Model" {
  [Usuario]
  [Aluno]
  [Professor]
  [Empresa]
  [Instituicao]
  [Vantagem]
  [Moeda]
  [Transacao]
  [Cupom]
}

' Conexões View -> Controller
[LoginPage] ..> [AuthController]
[DashboardAluno] ..> [AlunoController]
[DashboardProfessor] ..> [ProfessorController]
[DashboardEmpresa] ..> [EmpresaController]
[ExtratoView] ..> [TransacaoController]
[TrocaMoedaView] ..> [VantagemController]
[CadastroAlunoView] ..> [AlunoController]

' Conexões Controller -> Model
[AuthController] ..> [Usuario]
[AlunoController] ..> [Aluno]
[AlunoController] ..> [Instituicao]
[AlunoController] ..> [Cupom]
[ProfessorController] ..> [Professor]
[ProfessorController] ..> [Transacao]
[EmpresaController] ..> [Empresa]
[EmpresaController] ..> [Vantagem]
[VantagemController] ..> [Vantagem]
[TransacaoController] ..> [Transacao]
[TransacaoController] ..> [Usuario]

' Herança
[Usuario] <|-- [Aluno]
[Usuario] <|-- [Professor]
[Usuario] <|-- [Empresa]

@enduml
