@startuml
skinparam node {
  BackgroundColor #EEEEEE
  BorderColor Black
}

actor Usuario

node "Cliente (Navegador Web)" {
  component "Interface Web" as WebUI
}

node "Servidor de Aplicação" {
  component "Controllers" as AppController
  component "Services" as AppService
}

node "Servidor de Banco de Dados" {
  database "Banco de Dados" as DB
}

Usuario ..> WebUI : Usa a interface

WebUI ..> AppController : envia requisições
AppController --> AppService : chama métodos
AppService ..> DB : realiza operações

@enduml
