@startuml
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
  ArrowColor DarkBlue
  ActorBorderColor black
  ActorFontStyle bold
  UsecaseBorderColor Navy
  UsecaseFontColor DarkBlue
}

actor Usuario
actor Aluno
actor Professor
actor Empresa

package "Sistema de Moeda Estudantil" {

  usecase "Fazer login" as UC_Login
  usecase "Fazer cadastro" as UC_CadUsuario
  usecase "Cadastrar Aluno" as UC_CadAluno
  usecase "Atualizar Aluno" as UC_UpdAluno
  usecase "Cadastrar Empresa Parceira" as UC_CadEmpresa
  usecase "Atualizar Empresa Parceira" as UC_UpdEmpresa
  usecase "Visualizar extrato de moedas" as UC_Extrato
  usecase "Trocar moedas por vantagens" as UC_TrocaMoedas
  usecase "Receber cupom por email com código" as UC_EmailCupom
  usecase "Notificar Aluno" as UC_ReceberMoedas
  usecase "Distribuir moedas aos alunos" as UC_DistribuirMoedas
  usecase "Cadastrar vantagens" as UC_CadVantagem
  usecase "Receber email de confirmação com código" as UC_ConfirmacaoParceiro
}

Usuario --> UC_Login
Usuario --> UC_CadUsuario
Aluno --> UC_CadAluno
Aluno --> UC_UpdAluno
Aluno --> UC_Extrato
Aluno --> UC_TrocaMoedas

Professor --> UC_DistribuirMoedas
Professor --> UC_Extrato

Empresa --> UC_CadEmpresa
Empresa --> UC_UpdEmpresa
Empresa --> UC_CadVantagem
Empresa --> UC_ConfirmacaoParceiro

UC_TrocaMoedas --> UC_EmailCupom : <<include>>
UC_DistribuirMoedas --> UC_ReceberMoedas : <<include>>

@enduml
