@startuml
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
  ArrowColor DarkBlue
  ActorBorderColor black
  ActorFontStyle bold
  UsecaseBorderColor Navy
  UsecaseFontColor DarkBlue
}

actor Usuario
actor Aluno
actor Professor
actor Empresa

package "Sistema de Moeda Estudantil" {

  usecase "Fazer login" as UC_Login
  usecase "Fazer cadastro" as UC_CadAluno
  usecase "Visualizar extrato de moedas" as UC_Extrato
  usecase "Trocar moedas por vantagens" as UC_TrocaMoedas
  usecase "Receber cupom por email com código" as UC_EmailCupom
  usecase "Notificar Aluno" as UC_ReceberMoedas

  usecase "Distribuir moedas aos alunos" as UC_DistribuirMoedas
  usecase "Cadastrar vantagens" as UC_CadVantagem
  usecase "Receber email de confirmação com código" as UC_ConfirmacaoParceiro
}

Usuario <|-- Aluno
Usuario <|-- Professor
Usuario <|-- Empresa

Usuario --> UC_Login
Usuario --> UC_CadAluno

' Casos de uso do Aluno

Aluno --> UC_Extrato
Aluno --> UC_TrocaMoedas

' Casos de uso do Professor
Professor --> UC_DistribuirMoedas
Professor --> UC_Extrato

' Casos de uso da Empresa
Empresa --> UC_CadVantagem
Empresa --> UC_ConfirmacaoParceiro


' Relações include
UC_TrocaMoedas --> UC_EmailCupom : <<include>>
UC_DistribuirMoedas --> UC_ReceberMoedas : <<include>>

@enduml
